---
apiVersion: {{API_VERSION}}
kind: ClusterRole
metadata:
  name: conjur-authenticator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "serviceaccounts", "replicationcontrollers", "deploymentconfigs"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"] # OpenShift 3.7+
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
