---
apiVersion: v1
kind: Pod
metadata:
  name: inventory-unauthorized
spec:
  containers:
  - image: {{INVENTORY_TAG}}
    name: inventory
    command: ["sleep", "infinity"]
  - image: {{INVENTORY_TAG}}
    name: authenticator
    command: ["sleep", "infinity"]
