---
apiVersion: v1
kind: Service
metadata:
  name: inventory-deployment-cfg
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: inventory-deployment-cfg
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: inventory-deployment-cfg
spec:
  replicas: 1
    selector:
      matchLabels:
        app: inventory-deployment-cfg
  template:
    metadata:
      labels:
        app: inventory-deployment-cfg
    spec:
      containers:
      - image: {{INVENTORY_TAG}}
        name: inventory
        command: ["sleep", "infinity"]
      - image: {{INVENTORY_TAG}}
        name: authenticator
        command: ["sleep", "infinity"]
