---
apiVersion: v1
kind: Service
metadata:
  name: inventory-headless
  labels:
    app: inventory-headless
spec:
  selector:
    app: inventory-stateful
  ports:
  - port: 80
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-stateful
  labels:
    app: inventory-stateful
spec:
  serviceName: inventory-headless
  selector:
    matchLabels:
      app: inventory-stateful
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-stateful
    spec:
      containers:
      - image: {{INVENTORY_TAG}}
        name: inventory
        command: ["sleep", "infinity"]
      - image: {{INVENTORY_TAG}}
        name: authenticator
        command: ["sleep", "infinity"]
