<% require 'securerandom' %>

development:
  secret_key_base: "boop"
test:
  secret_key_base: "boop"
production:
  # Conjur doesn't use HTTP cookies or Rails key generation,
  # so we set secret_key_base to a random value on application startup. 
  secret_key_base: <%= SecureRandom.hex(64) %>
appliance:
  # Conjur doesn't use HTTP cookies or Rails key generation,
  # so we set secret_key_base to a random value on application startup.
  secret_key_base: <%= SecureRandom.hex(64) %>
